name: Rust

on:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install macOS build toochain
      run: rustup target add x86_64-apple-darwin
    - name: Build
      run: cargo build --release --target x86_64-apple-darwin --verbose
